[project]
name = "Vendange"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "uvicorn[standard]",
    "pydantic",
    "python-multipart",
    "rich>=14.2.0",
    "pip>=25.2",
    "numpy==1.26.4",
    "spacy>=3.8.7",
]