ontologyFile=./ontology.ttl
mappingFile=./mapping.obda
jdbc.url=jdbc:postgresql://postgres:5432/vendange
jdbc.user=vendange
jdbc.password=vendange
jdbc.driver=org.postgresql.Driver
port=8080
enable-ontologyAnnotations=true
enable-validation=false
