export const THEME_STORAGE_KEY = 'vendange:theme'
export const SHORTCUT_STORAGE_KEY = 'vendange:shortcuts'
export const CLUSTER_NOTE = 'Clusterisation script'
export const MANUAL_CLUSTER_NOTE = 'Clusterisation manuelle'
export const EXPRESSION_DRAG_MIME = 'application/x-expression-cluster'
export const MANIFESTATION_DRAG_MIME = 'application/x-manifestation-cluster'
export const FILE_DRAG_TYPE = 'Files'
